# Generated by Django 4.1.1 on 2022-09-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(verbose_name='Fecha de Publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_comment', models.CharField(max_length=1000)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblog.input')),
            ],
        ),
    ]
